"""Generate and verify human-readable Markdown paired with scenario JSON files."""

import argparse
import hashlib
import json
from pathlib import Path

VARIABLE_LABELS = {
    "anger": "愤怒", "anxiety": "焦虑", "hope": "希望",
    "resolve": "坚持推进意愿", "repair_intent": "关系修复意愿",
    "trust": "信任", "hostility": "敌意",
    "goal_failure_risk": "目标失败风险", "escalation_risk": "冲突升级风险",
    "negotiation_open": "协商开放度",
}
DELTA_LABELS = {
    "strong_decrease": "强烈下降（约 -3）", "moderate_decrease": "中度下降（约 -2）",
    "mild_decrease": "轻度下降（约 -1）", "similar": "基本不变（约 0）",
    "mild_increase": "轻度上升（约 +1）", "moderate_increase": "中度上升（约 +2）",
    "strong_increase": "强烈上升（约 +3）",
}
ACTION_LABELS = {"repair": "修复 / 合作", "neutral": "中性 / 观望", "escalate": "升级 / 对抗"}


def _flatten(values, prefix=""):
    rows = []
    for key, value in (values or {}).items():
        path = f"{prefix}.{key}" if prefix else key
        rows.extend(_flatten(value, path) if isinstance(value, dict) else [(path, value)])
    return rows


def _variable(path):
    leaf = path.split(".")[-1]
    return f"{VARIABLE_LABELS.get(leaf, leaf)} (`{path}`)"


def _table(values, deltas=False):
    lines = ["| 状态变量 | 变化方向 |" if deltas else "| 状态变量 | 初始值 |", "|---|---|"]
    for path, value in _flatten(values):
        rendered = DELTA_LABELS.get(value, value) if deltas else value
        lines.append(f"| {_variable(path)} | {rendered} |")
    return lines


def _expression(expression):
    labels = {"facial_expression": "面部表情", "gaze": "视线", "speech_style": "说话方式",
              "prosody": "语气/韵律", "behavioral_cues": "行为线索"}
    lines = []
    for key, value in (expression or {}).items():
        rendered = "；".join(map(str, value)) if isinstance(value, list) else value
        lines.append(f"- {labels.get(key, key)}：{rendered}")
    return lines or ["- 未配置。"]


def _mode_text(mode):
    return {"crossing": "前一轮尚未满足、当前轮首次满足全部阈值时触发",
            "threshold": "当前状态满足全部阈值时触发，并受冷却轮次限制",
            "state_change": "本轮变化量满足 change_conditions 时触发"}.get(mode, mode)


def scenario_hash(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def render_scenario_document(scenario, source_name, source_hash):
    agent = scenario["environment_agent"]
    persona = agent.get("persona", {})
    role = scenario.get("evaluated_agent_role", {})
    media = scenario.get("media_generation", {})
    lines = [
        "<!-- AUTO-GENERATED BY scripts/scenario_docs.py; EDIT JSON THEN REGENERATE. -->", "",
        f"# {scenario.get('title', scenario['scenario_id'])}", "", "## 文档身份", "",
        f"- Scenario ID：`{scenario['scenario_id']}`", f"- 配对 JSON：`{source_name}`",
        f"- JSON SHA-256：`{source_hash}`", f"- 社会机制：{scenario.get('mechanism', '未配置')}", "",
        "## 1. 故事初始化", "", f"故事背景：{scenario.get('background', '未配置')}", "",
        f"被评估角色：{role.get('name', role.get('character_id', '未配置'))}（`{role.get('character_id', 'unknown')}`）。", "",
        f"环境角色：{persona.get('name', '未配置')} / {persona.get('role', '未配置')}。耐心 `{persona.get('patience', '未配置')}`，共情 `{persona.get('empathy', '未配置')}`。", "",
        f"公开目标：{agent.get('explicit_goal', '未配置')}", "",
        f"隐藏意图（作者侧私有）：{agent.get('hidden_intention', '未配置')}", "",
        f"最长互动：`{scenario.get('max_turns', 20)}` 轮。初始回应：{scenario.get('opening_response') or '未配置，环境从空回应开始。'}", "",
        "### 初始 State（0–10）", "", "数值越高表示该状态越强；State 是环境内部变量。", "",
        *_table(scenario.get("initial_state", {})), "", "### 初始 Interaction Dynamics（0–10）", "",
        *_table(scenario.get("initial_dynamics", {})), "", "### 重点预测状态", "",
        *[f"- {_variable(item)}" for item in scenario.get("target_state_ids", [])], "",
        "## 2. Action 对 State 的影响", "",
        "语义标签映射到 -3 至 +3，更新后截断在 0–10。Persona modifier 可以改变幅度，但不会反转非零方向。", "",
    ]
    cues, templates = scenario.get("observable_cues_by_action", {}), scenario.get("response_templates", {})
    for action_id, effect in scenario.get("action_effects", {}).items():
        lines.extend([
            f"### `{action_id}` — {ACTION_LABELS.get(action_id, action_id)}", "",
            f"目标一致性：`{effect.get('goal_alignment', 'unknown')}`。", "", "State 变化：", "",
            *_table(effect.get("state_delta", {}), True), "", "Interaction dynamics 变化：", "",
            *_table(effect.get("interaction_dynamics_delta", {}), True), "",
            "可观察线索：" + ("；".join(cues.get(action_id, [])) or "未配置。"), "",
            "回应模板：" + (templates.get(action_id) or templates.get("default") or "未配置。"), "",
        ])
    lines.extend([
        "## 3. Talking Head / 视频生成", "", "### 默认外显表达", "",
        *_expression(scenario.get("observable_expression", {}).get("default", {})), "", "### 媒体生成配置", "",
        f"- 阶段：`{media.get('stage', '未配置')}`", f"- 默认媒体类型：`{media.get('default_media_type', '未配置')}`",
        f"- 资产状态：`{media.get('asset_status', '未配置')}`", f"- 资产根目录：`{media.get('asset_root', '未配置')}`",
        f"- 说明：{media.get('note', '未配置')}", "", "### 视频触发规则", "",
        "同一规则的 conditions 按 AND 判断，必须全部满足。阈值和 trigger ID 保留在私有 trajectory；公开 observation 只获得 expression 与安全 media spec。", "",
    ])
    triggers = scenario.get("video_triggers", [])
    if not triggers:
        lines.extend(["当前 scenario 未配置视频触发规则。", ""])
    for trigger in triggers:
        mode = trigger.get("trigger_mode", "crossing")
        lines.extend([f"#### `{trigger['trigger_id']}`", "", f"触发模式：`{mode}`，即{_mode_text(mode)}。", "", "阈值条件：", ""])
        lines.extend(f"- {_variable(variable)} {condition.get('operator')} `{condition.get('threshold')}`"
                     for variable, condition in trigger.get("conditions", {}).items())
        if trigger.get("change_conditions"):
            lines.extend(["", "变化量条件：", ""])
            lines.extend(f"- {_variable(variable)} 的本轮变化量 {condition.get('operator')} `{condition.get('threshold')}`"
                         for variable, condition in trigger["change_conditions"].items())
        lines.extend(["", f"冷却 `{trigger.get('cooldown_turns', 0)}` 轮；媒体 `{trigger.get('media_type', 'video')}`；时长 `{trigger.get('duration_seconds', 4)}` 秒；cue template `{trigger.get('cue_template', '未配置')}`。",
                      "", "触发后的外显表达：", "", *_expression(trigger.get("observable_expression", {})), ""])
    sampling = scenario.get("sampling_plan", {})
    lines.extend(["## 4. Pipeline 配套", "",
                  f"- T1/T2/T3 最大候选数：`{sampling.get('t1_max', '未配置')}` / `{sampling.get('t2_max', '未配置')}` / `{sampling.get('t3_max', '未配置')}`",
                  f"- T3 delayed horizon：`{scenario.get('t3_delayed_horizon', '未配置')}`",
                  f"- 采样：`{sampling.get('selection_strategy', '未配置')}`，seed `{sampling.get('seed', '未配置')}`", "",
                  "修改 JSON 后执行：", "", "```bash",
                  f"python scripts/scenario_docs.py configs/scenarios/{source_name}",
                  "python -m scripts.run_pipeline --scenarios configs/scenarios --output build/pipeline_v1", "```", ""])
    return "\n".join(lines)


def expected_document(json_path):
    json_path = Path(json_path)
    scenario = json.loads(json_path.read_text(encoding="utf-8"))
    return render_scenario_document(scenario, json_path.name, scenario_hash(json_path))


def write_document(json_path):
    json_path = Path(json_path)
    output = json_path.with_suffix(".md")
    output.write_text(expected_document(json_path), encoding="utf-8")
    return output


def assert_document_current(json_path):
    json_path = Path(json_path)
    output = json_path.with_suffix(".md")
    if not output.exists():
        raise ValueError(f"scenario documentation missing: {output}; run scripts/scenario_docs.py")
    if output.read_text(encoding="utf-8") != expected_document(json_path):
        raise ValueError(f"scenario documentation is stale: {output}; regenerate it from {json_path}")
    return output


def manifest_payload(directory):
    directory = Path(directory)
    scenarios = []
    for path in sorted(directory.glob("scenario_*.json")):
        scenario = json.loads(path.read_text(encoding="utf-8"))
        scenarios.append({
            "scenario_id": scenario["scenario_id"],
            "title": scenario.get("title", scenario["scenario_id"]),
            "mechanism": scenario.get("mechanism", ""),
            "source": path.name,
            "documentation": path.with_suffix(".md").name,
        })
    return {
        "format": "emotree_scenario_manifest_v1",
        "scenario_count": len(scenarios),
        "scenarios": scenarios,
    }


def write_manifest(directory):
    directory = Path(directory)
    output = directory / "manifest.json"
    output.write_text(
        json.dumps(manifest_payload(directory), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return output


def assert_manifest_current(directory):
    directory = Path(directory)
    output = directory / "manifest.json"
    expected = json.dumps(manifest_payload(directory), ensure_ascii=False, indent=2) + "\n"
    if not output.exists() or output.read_text(encoding="utf-8") != expected:
        raise ValueError(
            f"scenario manifest is missing or stale: {output}; run scripts/scenario_docs.py"
        )
    return output


def main():
    parser = argparse.ArgumentParser(description="Generate paired Markdown for scenario JSON files")
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    paths = args.paths or sorted(Path("configs/scenarios").glob("scenario_*.json"))
    if not paths:
        parser.error("no scenario JSON files found")
    for path in paths:
        output = assert_document_current(path) if args.check else write_document(path)
        print(f"{'checked' if args.check else 'generated'} {output}")
    for directory in sorted({path.parent for path in paths}):
        manifest = assert_manifest_current(directory) if args.check else write_manifest(directory)
        print(f"{'checked' if args.check else 'generated'} {manifest}")


if __name__ == "__main__":
    main()
